{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-prometheus-config
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
data:
  prometheus.yml: |
    {{- /* 1. Convert the entire 'config' section from values.yaml into a string */ -}}
    {{- $configString := toYaml .Values.config }}

    {{- /* 2. Process that string as a template (resolving {{ .Release.Name }} etc.) */ -}}
    {{- tpl $configString . | nindent 4 }}
{{- end }}