annotations:
  category: DeveloperTools
  bitnamiVersion: 10.1.6
apiVersion: v2
appVersion: 19.0.2
dependencies:
- name: common
  repository: file://charts/common
  tags:
  - bitnami-common
  version: 2.0.3
description: Keycloak is a high performance Java-based identity and access management solution. It lets developers add an authentication layer to their applications with minimum effort.
home: https://www.keycloak.org
icon: https://bitnami.com/assets/stacks/keycloak/img/keycloak-stack-220x234.png
keywords:
- keycloak
- access-management
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: keycloak
sources:
- https://github.com/bitnami/containers/tree/main/bitnami/keycloak
- https://github.com/keycloak/keycloak
version: 4.10.4
