annotations:
  category: Infrastructure
  bitnamiVersion: 11.10.6
apiVersion: v2
appVersion: 2022.10.5
dependencies:
- name: common
  repository: file://charts/common
  tags:
  - bitnami-common
  version: 2.x.x
description: MinIO(R) is an object storage server, compatible with Amazon S3 cloud
  storage service, mainly used for storing unstructured data (such as photos, videos,
  log files, etc.).
home: https://github.com/bitnami/charts/tree/master/bitnami/minio
icon: https://bitnami.com/assets/stacks/minio/img/minio-stack-220x234.png
keywords:
- minio
- storage
- object-storage
- s3
- cluster
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: minio
sources:
- https://github.com/bitnami/containers/tree/main/bitnami/minio
- https://min.io
version: 5.0-alpha
