annotations:
  bitnamiVersion: 0.7.5
apiVersion: v2
appVersion: "1.0"
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: file://charts/postgresql
  version: 11.1.22
- condition: redis.enabled
  name: redis
  repository: file://charts/redis
  version: 16.3.1
description: Apache Superset is a modern, enterprise-ready business intelligence web
  application
maintainers:
- email: craig@craigrueda.com
  name: craig-rueda
  url: https://github.com/craig-rueda
name: superset
version: 4.10.4
